# Generated by Django 3.2.3 on 2021-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=30)),
                ('contra', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
