# Generated by Django 3.2.4 on 2021-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='intentos_por_ip',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('contador', models.IntegerField(default=0)),
                ('ultima_peticion', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='duracion',
            field=models.DateTimeField(null=True),
        ),
    ]
