# Generated by Django 3.2.4 on 2021-06-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20210620_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contra',
            field=models.CharField(max_length=100),
        ),
    ]
