# Generated by Django 3.2.4 on 2021-06-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_alter_usuarios_contra'),
    ]

    operations = [
        migrations.CreateModel(
            name='credenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncuenta', models.CharField(max_length=30)),
                ('usuarioa', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=60)),
                ('detalles', models.CharField(max_length=60)),
                ('iv', models.CharField(max_length=60)),
            ],
        ),
    ]
