# Generated by Django 3.2.4 on 2021-06-25 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0009_rename_ncuenta_credenciales_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credenciales',
            old_name='cuenta',
            new_name='nombre_cuenta',
        ),
        migrations.RemoveField(
            model_name='credenciales',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='credenciales',
            name='usuarioa',
        ),
        migrations.AddField(
            model_name='credenciales',
            name='contra_cuenta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='credenciales',
            name='usuario_asociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.usuarios'),
        ),
        migrations.AddField(
            model_name='credenciales',
            name='usuario_cuenta',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='salt',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='credenciales',
            name='detalles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='credenciales',
            name='iv',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='credenciales',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contra',
            field=models.CharField(max_length=100),
        ),
    ]
