# Generated by Django 3.2.3 on 2021-06-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0010_auto_20210624_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciales',
            name='detalles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='credenciales',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
